/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import jogo.Jogo;
import java.io.FileInputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lojapokemon.Loja;

/**
 *
 * @author mazzoco
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private String propertiesPath;
    Properties props;
    FileInputStream file;
    
    public App(String propertiesPath) throws Exception{
        this.propertiesPath = propertiesPath;      
        props = new Properties();
        file = new FileInputStream(propertiesPath);
        props.load(file);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ver_Recorde = new javax.swing.JButton();
        Iniciar_Jogo = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        Loja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Pokemon");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver_Recorde.setText("Ver Recorde");
        Ver_Recorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_RecordeActionPerformed(evt);
            }
        });
        getContentPane().add(Ver_Recorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, -1));

        Iniciar_Jogo.setText("Iniciar Jogo");
        Iniciar_Jogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_JogoActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar_Jogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, -1));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poke2.jpg"))); // NOI18N
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Loja.setText("Loja");
        Loja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LojaActionPerformed(evt);
            }
        });
        getContentPane().add(Loja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Ver_RecordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_RecordeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Recorde Atual : " + props.getProperty("prop.jogo.recorde"));
    }//GEN-LAST:event_Ver_RecordeActionPerformed

    private void Iniciar_JogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_JogoActionPerformed
        // TODO add your handling code here:
        
        String nomes = props.getProperty("prop.pokemons.nomes");     
        String tipos = props.getProperty("prop.pokemons.tipos");
        Jogo j;
        try {
            j = new Jogo(propertiesPath);
            j.iniciarPokedex(nomes, tipos);
            j.iniciarJogo();
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Iniciar_JogoActionPerformed

    private void LojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LojaActionPerformed
        /*Se tivesse entendido que era para existir uma classe PokemonBrinquedo,
        faria ela com os atributos Nome e Preco, e listaria eles com a pokedex do
        mesmo jeito que e feito com os pokemons normais, o que iria mudar seria
        a alocacao dos objetos quando escolhidos e retornados para a funcao
        que faz a venda, necessitando assim de uma funcao de escolha de pokemons 
        diferente da que foi usada.E guardar os escolhidos em um ArrayList para 
        posteriormente guardar em um arquivo txt com as informacoes da venda.*/
        try {
            Loja l = new Loja(propertiesPath);
            l.comprar();
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new App(args[0]).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar_Jogo;
    private javax.swing.JButton Loja;
    private javax.swing.JButton Ver_Recorde;
    private javax.swing.JLabel jLabelImage;
    // End of variables declaration//GEN-END:variables
}
